# Generated by Django 4.0.1 on 2022-06-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered_quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
