# Generated by Django 4.0.1 on 2022-06-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_records_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
